### ISSUE TITLE
Bonsai Tree Integration disables Slime Saplings from TCon in Bonsai Trees

### ISSUE THREAD

**Issue by EctoOne** [BeetoGuy/ApricornTreeFarm#2]
I just updated my personal Pack to Pixelmon 7.0.3 and noticed an issue with your mod.
I wasn't able to plant any slime saplings from Tinker's Construct in Bonsai Pots from Bonsai Trees.

I copied the config files from your jar to the default minecraft config folder and deleted the bonsaitrees folder in the assets folde afterwards. That worked out.

Tested with:
(Working)
* Minecraft 1.12.2
* Forge 2768
* Bonsai Trees 1.12-b144
* Mantle 1.3.3.42
* Tinker's Contruct 1.12.2-2.12.0.115

(Not Working)
* Pixelmon 7.0.3
* Apricorn Tree Farm 1.12.2-2.0.4

I don't know if other mods affected by this, vanilla saplings worked though.

**Comment by BeetoGuy** [comment]
If that's the case, then I'll remove Bonsai Trees compatibility and upload the config files as a separate zip file.

**Comment by EctoOne** [comment]
Thanks. I guess directly submitting a PR with the files to Bonsai Trees wouldn't be downward compatible with Pixelmon. So I can't think of any other solution.

**Comment by EctoOne** [comment]
@BeetoGuy The issue still exists in the 2.0.5 update. There are still bonsai trees related folders in the assets folder of the jar.
