### ISSUE TITLE
Server crashing whenever a shiny is bred

### ISSUE THREAD

**Issue by Xrkerr** [BeetoGuy/ApricornTreeFarm#6]
Whenever a shiny egg is bred with the shiny parent option(GEN 2 Mechanic) enabled, it crashes my server without exception.
My version of Pixelmon is the latest Reforged.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  CoreModBase (ShulkerBoxViewer-1.5-mc[1.11-1.12.2].jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  SpongeCoremod (spongeforge-1.12.2-2838-7.2.0.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 1/12/21 2:43 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: com.pixelmonmod.pixelmon.storage.PlayerPartyStorage.getShinyCharm()Lcom/pixelmonmod/pixelmon/enums/EnumShinyCharm;
	at apritree.event.ShinyPokemonEventHandler.onPixelmonBred(ShinyPokemonEventHandler.java:57)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_194_ShinyPokemonEventHandler_onPixelmonBred_MakeEgg.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703)
	at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.updateStatus(TileEntityRanchBlock.java:242)
	at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.updateBreeding(TileEntityRanchBlock.java:222)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.func_73660_a(TileEntityRanchBlock.java:168)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4726)
	at net.minecraft.world.WorldServer.redirect$zlj000$onUpdateTileEntities(WorldServer.java:4710)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3928)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at apritree.event.ShinyPokemonEventHandler.onPixelmonBred(ShinyPokemonEventHandler.java:57)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_194_ShinyPokemonEventHandler_onPixelmonBred_MakeEgg.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703)
	at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.updateStatus(TileEntityRanchBlock.java:242)
	at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.updateBreeding(TileEntityRanchBlock.java:222)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.func_73660_a(TileEntityRanchBlock.java:168)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4726)
	at net.minecraft.world.WorldServer.redirect$zlj000$onUpdateTileEntities(WorldServer.java:4710)

-- Block entity being ticked --
Details:
	Name: pixelmon:ranch_block // com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock
	Block type: ID #1052 (tile.ranch // com.pixelmonmod.pixelmon.blocks.ranch.BlockRanchBlock // pixelmon:ranch)
	Block data value: 10 / 0xA / 0b1010
	Block location: World: (248,66,1391), Chunk: (at 8,4,15 in 15,86; contains blocks 240,0,1376 to 255,255,1391), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Actual block type: ID #1052 (tile.ranch // com.pixelmonmod.pixelmon.blocks.ranch.BlockRanchBlock // pixelmon:ranch)
	Actual block data value: 10 / 0xA / 0b1010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3928)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['MiNii_NinjaZ'/25, l='world', x=201.20, y=79.00, z=1394.87], EntityPlayerMP['Lunashy145'/2460, l='world', x=-23055.16, y=68.00, z=4910.76]]
	Chunk stats: ServerChunkCache: 1219 Drop: 0
	Level seed: 5289436259467347408
	Level generator: ID 11 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (24,68,1227), Chunk: (at 8,4,11 in 1,76; contains blocks 16,0,1216 to 31,255,1231), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Level time: 6304647 game time, 6107698 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 32590 (now: false), thunder time: 29123 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$zje000$onCrashReport(MinecraftServer.java:4687)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 2.6.32-openvz-042stab139.1-amd64
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 116837992 bytes (111 MB) / 1507483648 bytes (1437 MB) up to 4670816256 bytes (4454 MB)
	JVM Flags: 7 total; -Xmx4608m -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
	IntCache: cache: 2, tcache: 103, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	Mods:

	| State  | ID                  | Version                  | Source                                            | Signature                                |
	|:------ |:------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                 | 9.42                     | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                | server.jar                                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838             | server.jar                                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | spongeapi           | 7.2-fe189dcf             | spongeforge-1.12.2-2838-7.2.0.jar                 | None                                     |
	| LCHIJA | sponge              | 1.12.2-7.2.0             | spongeforge-1.12.2-2838-7.2.0.jar                 | None                                     |
	| LCHIJA | spongeforge         | 1.12.2-2838-7.2.0        | spongeforge-1.12.2-2838-7.2.0.jar                 | None                                     |
	| LCHIJA | bspkrscore          | 7.6.0.1                  | [1.12]bspkrsCore-universal-7.6.0.1.jar            | None                                     |
	| LCHIJA | treecapitator       | 1.43.0                   | [1.12]TreeCapitator-client-1.43.0.jar             | None                                     |
	| LCHIJA | pixelmon            | 8.1.2                    | Pixelmon-1.12.2-8.1.2-universal.jar               | None                                     |
	| LCHIJA | apritree            | 2.4.0                    | ApriTree-2.4.0.jar                                | None                                     |
	| LCHIJA | crafttweaker        | 4.1.20                   | CraftTweaker2-1.12-4.1.20.594.jar                 | None                                     |
	| LCHIJA | jei                 | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                         | None                                     |
	| LCHIJA | athenaeum           | 1.12.2-1.19.2            | athenaeum-1.12.2-1.19.2.jar                       | None                                     |
	| LCHIJA | autocrafter         | 4.3                      | autocrafter-4.3.jar                               | None                                     |
	| LCHIJA | biomesoplenty       | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar     | None                                     |
	| LCHIJA | bonsaitrees         | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                        | None                                     |
	| LCHIJA | bop_patch           | 1.0                      | BOP-Patch-1.0.jar                                 | None                                     |
	| LCHIJA | chameleon           | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCHIJA | chisel              | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                      | None                                     |
	| LCHIJA | codechickenlib      | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | mantle              | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LCHIJA | tconstruct          | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                  | None                                     |
	| LCHIJA | conarm              | 1.2.5.9                  | conarm-1.12.2-1.2.5.9.jar                         | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | craftingautomat     | 1.0.5                    | CraftingAutomat-MC1.12.2-1.0.5.jar                | None                                     |
	| LCHIJA | crafttweakerjei     | 2.0.3                    | CraftTweaker2-1.12-4.1.20.594.jar                 | None                                     |
	| LCHIJA | cxlibrary           | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                        | None                                     |
	| LCHIJA | dexnav              | 1.0.0                    | DexNav-1.0.2.jar                                  | None                                     |
	| LCHIJA | enderstorage        | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | extrautils2         | 1.0                      | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| LCHIJA | fastbench           | 1.7.3                    | FastWorkbench-1.12.2-1.7.3.jar                    | None                                     |
	| LCHIJA | cfm                 | 6.3.1                    | furniture-6.3.1-1.12.2.jar                        | None                                     |
	| LCHIJA | harvest             | 1.12-1.2.6-18            | Harvest-1.12-1.2.6-18.jar                         | None                                     |
	| LCHIJA | waila               | 1.8.26                   | hwyla-1-8-26-b41-1-12-2-jar.jar                   | None                                     |
	| LCHIJA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironbackpacks       | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
	| LCHIJA | itemfilters         | 1.0.4.2                  | ItemFilters-1.0.4.2.jar                           | None                                     |
	| LCHIJA | ivchain             | 1.2.2                    | IVChain-1.2.4.jar                                 | None                                     |
	| LCHIJA | legendaryplus       | 6.0                      | LegendaryPlus-6.0.jar                             | None                                     |
	| LCHIJA | mca                 | 6.1.0                    | MCA-1.12.2-6.1.0-universal.jar                    | None                                     |
	| LCHIJA | mekanism            | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                     | None                                     |
	| LCHIJA | mekanismgenerators  | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar           | None                                     |
	| LCHIJA | morefurnaces        | 1.10.5                   | MoreFurnaces-1.12.2-1.10.6.jar                    | None                                     |
	| LCHIJA | pixelextras         | 2.5.4                    | pixelExtras-1.12.2-2.5.4-universal.jar            | None                                     |
	| LCHIJA | pixelmoninformation | 0.3.7                    | PixelmonInformation-1.12.2-8.0.0-0.3.7 (1).jar    | None                                     |
	| LCHIJA | valkyrielib         | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar                   | None                                     |
	| LCHIJA | simplegenerators    | 1.12.2-2.0.20.2          | simplegenerators-1.12.2-2.0.20.2.jar              | None                                     |
	| LCHIJA | storagedrawers      | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0 (1).jar               | None                                     |
	| LCHIJA | storagedrawersextra | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar               | None                                     |
	| LCHIJA | tinkertoolleveling  | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
	| LCHIJA | unknownlibs         | 1.1.2                    | UnknownLibs-1.1.2.jar                             | None                                     |
	| LCHIJA | universalmodifiers  | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar                   | None                                     |
	| LCHIJA | veinminer           | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| LCHIJA | veinminermodsupport | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| LCHIJA | watercan            | 1.12.2-1.1.3             | watercan-1.12.2-1.1.3.jar                         | None                                     |
	| LCHIJA | worldedit           | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Plugins:

	| State  | ID                       | Version            | Source                                    | Signature |
	|:------ |:------------------------ |:------------------ |:----------------------------------------- |:--------- |
	| LCHIJA | aurorabackup             | 7.2-1.0.0-SNAPSHOT | AuroraBackup-7.2-1.0.0-SNAPSHOT.jar       | None      |
	| LCHIJA | catclearlag              | 0.9.0              | CatClearLag-0.9.0.jar                     | None      |
	| LCHIJA | evenmorepixelmoncommands | 5.1.3              | EvenMorePixelmonCommands-1.12.2-5.1.3.jar | None      |
	| LCHIJA | fusionpixelmon           | 1.11               | FusionPixelmon-1.11-sponge.jar            | None      |
	| LCHIJA | holograms                | 3.1.5              | holograms-3.1.5.jar                       | None      |
	| LCHIJA | huskyui                  | 0.6.0PRE4          | HuskyUI-v0.6.0-PRE4-API7.jar              | None      |
	| LCHIJA | huskycrates              | 2.0.0RC3           | HuskyCrates.jar                           | None      |
	| LCHIJA | karoglansigneditor       | 3.4.1              | KaroglanSignEditor-3.4.1.jar              | None      |
	| LCHIJA | langswitch               | 1.6.1              | LangSwitch-1.6.1.jar                      | None      |
	| LCHIJA | luckperms                | 5.2.77             | LuckPerms-Sponge-5.2.77.jar               | None      |
	| LCHIJA | megamenus                | 0.8                | MegaMenus-0.8.jar                         | None      |
	| LCHIJA | nucleus                  | 1.14.6-S7.1        | Nucleus-1.14.6-S7.1-MC1.12.2-plugin.jar   | None      |
	| LCHIJA | pixelbuilt-quests        | 3.3                | PixelBuilt-Quests-3.3.jar                 | None      |
	| LCHIJA | chatpixel                | 1.80               | PixelChat-1.80.jar                        | None      |
	| LCHIJA | pixelhunt                | 1.1.3              | PixelHunt-1.1.3-MC1.12.2-S7.2.0.jar       | None      |
	| LCHIJA | simpledexrewards         |                    | SimpleDexRewards-1.0.1-RELEASE-.jar       | None      |
	| LCHIJA | vshop                    | 2.8.2              | VillagerShops-2.8.2.jar                   | None      |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
CoreModBase (ShulkerBoxViewer-1.5-mc[1.11-1.12.2].jar)
  com.dazo66.shulkerboxshower.asm.MainTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
SpongeCoremod (spongeforge-1.12.2-2838-7.2.0.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 2 / 40; [EntityPlayerMP['MiNii_NinjaZ'/25, l='world', x=201.20, y=79.00, z=1394.87], EntityPlayerMP['Lunashy145'/2460, l='world', x=-23055.16, y=68.00, z=4910.76]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by BeetoGuy** [comment]
Oh right, I forgot the latest version changed that method name.

**Comment by BeetoGuy** [comment]
Actually, now that I checked, it shouldn't be doing that. I might just block out that section entirely.
