### ISSUE TITLE
Missing Bonsai Tree Compatibility

### ISSUE THREAD

**Issue by Xrkerr** [BeetoGuy/ApricornTreeFarm#7]
Hey! Back again with something that is more of a question as opposed to a serious issue.

As the title suggests, there are a few saplings that are not compatible with the Bonsai Pots mod, these being the **_Wavy_**, **_Crimson_** and **_Shiny_** saplings.
Is this intentional design or am I just missing some configs files?

Thank you in advance and I apologise for taking up time for such a simplistic question.

**Comment by BeetoGuy** [comment]
The config files haven't been updated, mostly because I stopped using Bonsai Tree in my personal packs due to rendering issues with some other mods I run.

**Comment by Xrkerr** [comment]
I see, will there be an eventual update for these?
If not, is there any direction you could point to learn how to do it?

Thank you!

**Comment by BeetoGuy** [comment]
Looking in my archive, it looks like I already have shiny and crimson configured, so I can just do the wavy apricorn trees and upload it.

**Comment by BeetoGuy** [comment]
The latest config files can be found here: https://www.curseforge.com/minecraft/mc-mods/apricorn-tree-farm/files/3179032
